# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_type.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='task_type.proto',
  package='g2p',
  syntax='proto2',
  serialized_pb=_b('\n\x0ftask_type.proto\x12\x03g2p*;\n\x08TaskType\x12\t\n\x05TRAIN\x10\x00\x12\x0c\n\x08\x45VALUATE\x10\x01\x12\x08\n\x04NONE\x10\x02\x12\x0c\n\x08SHUTDOWN\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TASKTYPE = _descriptor.EnumDescriptor(
  name='TaskType',
  full_name='g2p.TaskType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRAIN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVALUATE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NONE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHUTDOWN', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=24,
  serialized_end=83,
)
_sym_db.RegisterEnumDescriptor(_TASKTYPE)

TaskType = enum_type_wrapper.EnumTypeWrapper(_TASKTYPE)
TRAIN = 0
EVALUATE = 1
NONE = 2
SHUTDOWN = 3


DESCRIPTOR.enum_types_by_name['TaskType'] = _TASKTYPE


# @@protoc_insertion_point(module_scope)
