# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker_status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='worker_status.proto',
  package='g2p',
  syntax='proto2',
  serialized_pb=_b('\n\x13worker_status.proto\x12\x03g2p*~\n\x0cWorkerStatus\x12\x08\n\x04IDLE\x10\x00\x12\x0b\n\x07WORKING\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x08\n\x04\x44ONE\x10\x03\x12\x0b\n\x07PENDING\x10\x04\x12\x10\n\x0c\x44ISCONNECTED\x10\x05\x12\x11\n\rSHUTTING_DOWN\x10\x06\x12\x10\n\x0cRECONNECTING\x10\x07')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_WORKERSTATUS = _descriptor.EnumDescriptor(
  name='WorkerStatus',
  full_name='g2p.WorkerStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORKING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DONE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PENDING', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISCONNECTED', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHUTTING_DOWN', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECONNECTING', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=28,
  serialized_end=154,
)
_sym_db.RegisterEnumDescriptor(_WORKERSTATUS)

WorkerStatus = enum_type_wrapper.EnumTypeWrapper(_WORKERSTATUS)
IDLE = 0
WORKING = 1
ERROR = 2
DONE = 3
PENDING = 4
DISCONNECTED = 5
SHUTTING_DOWN = 6
RECONNECTING = 7


DESCRIPTOR.enum_types_by_name['WorkerStatus'] = _WORKERSTATUS


# @@protoc_insertion_point(module_scope)
