# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker_type.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='worker_type.proto',
  package='g2p',
  syntax='proto2',
  serialized_pb=_b('\n\x11worker_type.proto\x12\x03g2p*\x1e\n\nWorkerType\x12\x07\n\x03\x43PU\x10\x01\x12\x07\n\x03GPU\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_WORKERTYPE = _descriptor.EnumDescriptor(
  name='WorkerType',
  full_name='g2p.WorkerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CPU', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GPU', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=26,
  serialized_end=56,
)
_sym_db.RegisterEnumDescriptor(_WORKERTYPE)

WorkerType = enum_type_wrapper.EnumTypeWrapper(_WORKERTYPE)
CPU = 1
GPU = 2


DESCRIPTOR.enum_types_by_name['WorkerType'] = _WORKERTYPE


# @@protoc_insertion_point(module_scope)
